name: "Create cluster using Minkube"
on: [pull_request, push]

jobs:
  minikube-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.0
      with:
        minikube-version: 1.4.0
        k8s-version: 1.15.1
    - name: Testing
      run: |
        egrep -c '(vmx|svm)' /proc/cpuinfo
        cat /sys/hypervisor/properties/capabilities
        virt-host-validate
        docker-machine-driver-kvm2 version
        minikube config set vm-driver kvm2
        minikube config set kubernetes-version v1.15.1
        minikube start
        minikube update-context
        kubectl cluster-info
