name: "Create cluster using Minkube"
on: [pull_request, push]

jobs:
  minikube-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.0
      with:
        minikube-version: 1.4.0
        k8s-version: 1.15.1
    - name: Testing
      run: |
        sudo apt update &> apt-update.log
        sudo apt install qemu-kvm libvirt-daemon-system libvirt-clients &> apt-install.log
        sudo usermod -G libvirt -a runner
        newgrp libvirt
        virsh --version
        wget https://github.com/kubernetes/minikube/releases/download/v0.30.0/docker-machine-driver-kvm2 -O /home/runner/bin/docker-machine-driver-kvm2
        chmod +x /home/runner/bin/docker-machine-driver-kvm2
        docker-machine-driver-kvm2
        ls -l /home/runner/bin
        minikube config set disk-size 3GB
        minikube config set vm-driver kvm2
        minikube start --alsologtostderr -v=8
        minikube update-context
        kubectl cluster-info
